### ISSUE TITLE
Add in an "auto-redeem" for coin items

### ISSUE THREAD

**Issue by Huskie** [martellaj/shortfuts#11]
Seems to make sense? This is the only item type I've come across that can't be handled currently. Proposal would be to auto-force a click on the redeem button?

**Comment by martellaj** [comment]
I think a good solution would be to handle it with same shortcut as "quick sell". Instead of immediately looking for and clicking the "Quick Sell" button in the details pane, we'd first search for "Redeem". I think the actions are similar enough that it would make sense. What do you think?

**Comment by Huskie** [comment]
That would work. The only concern I can see is whether it's intuitive enough to fall under the same keyboard shortcut as Quick Sell. I guess as long as it's added to the docs then it shouldn't be a problem. If you're happy I will work on this later.

**Comment by martellaj** [comment]
I'd also argue that we could do the same check in "Send to My Club" action. I can rationalize it by saying "I want to store the coins in my club" or "I want to sell the item to get the coin value". That way, either way someone thinks about it, they could redeem the item using "s" or "q".

**Comment by Huskie** [comment]
Sounds good 👍  I can work on this so feel free to assign.

**Comment by martellaj** [comment]
Completed with f8d776f.

@Huskie, I took a slightly different route and implemented it myself. I changed `pressDetailsPaneButton` to only press if the string matches AND it's not hidden. If it fails, I throw an exception, and the caller (in this case, `quickSell` and `storeInClub`) handles it by calling it again, but trying to press "Redeem".
