### ISSUE TITLE
Chrome extension install makes icon tiny

### ISSUE THREAD

**Issue by SubNoizey** [martellaj/shortfuts#12]
Loading from Dev options loaded the full size icon in the toolbar, installing it from the extension store makes it tiny.

**Comment by martellaj** [comment]
They are different icons. That's the recommended size from Google. You're right though, I'm changing it. Google can suck it.


<sup>Just kidding in case one day I decide to interview there and they find this.</sup>

**Comment by martellaj** [comment]
Fixed in version 1.0.2 that's getting published now.
