### ISSUE TITLE
Add "Send All to Club" shortfut

### ISSUE THREAD

**Issue by fifa2017player** [martellaj/shortfuts#21]
These would be great to add if possible, thanks!

**Comment by fifa2017player** [comment]
I tried to implement Clear Expired, but it seems when I call tapElement on the section header buttons, nothing seems to happen.

```
var selector = 'div:contains("Clear Expired"):visible';
var element = $(selector)[0];
tapElement(element);
```

Same goes for Clear Sold, Relist All, those buttons that appear at the top of a list of items. Wonder if some different sequence of events might be necessary to trigger them?

Thanks!

**Comment by martellaj** [comment]
Yep. If you search and read through other issues, you'll find similar notes. That's why that hasn't been implemented yet. Please submit a PR if you get something with though. 👍🏻

On mobile, so please excuse any errors or brevity.
________________________________

**Comment by martellaj** [comment]
Original title: "[request] shortcuts to clear expired, clear sold, relist all, send all to club"

The technique behind all of these asks will be the same, so just targeting one for this issue. If I could solve it, it'll enable me to add shortcuts for each one.
