### ISSUE TITLE
Add "Quick Sell All" shortcut

### ISSUE THREAD

**Issue by imCalebM** [martellaj/shortfuts#27]
Tried to implement my own but failed, would be a great feature if you can get it working

**Comment by martellaj** [comment]
Yeah, I tried the other day (#3) and couldn't get it either. I'll leave this open though. Hope to figure it out.

**Comment by imCalebM** [comment]
I tried using your tapButton to click on it, and also just a looping quick sell for each remaining item but it's far too slow

**Comment by martellaj** [comment]
Yeah, I had implemented (and maybe checked in?) a fallback command to just loop through the items and individually quick sell, but it's far slower than just clicking the button with the mouse so I removed it.

**Comment by martellaj** [comment]
@imCalebM Added in 3.1.0!
