### ISSUE TITLE
Fix buyBronzePack bug when it buys a silver pack

### ISSUE THREAD

**Issue by martellaj** [martellaj/shortfuts#28]
@Huskie, I just hit this bug. While I accidentally bought a silver pack and earned about 10k, I agree it should be fixed. I know you've investigated, so I'll leave it open for you to fix. 👍 

Let me know if you don't want it - I can take it, too.

**Comment by martellaj** [comment]
@Huskie I just published version 2.1.2 that contains this fix... after I opened up a bullshit silver pack because promo packs are in the store. -_-

**Comment by Huskie** [comment]
:sunglasses:
