### ISSUE TITLE
Futbin data

### ISSUE THREAD

**Issue by andreiiulian90** [martellaj/shortfuts#44]
This is the error from the console

Failed to load https://www.futbin.com/18/playerPrices?player=200529: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://dcmhogfnodefoildnphkcfcjaamoahkb' is therefore not allowed access.
commonUtility.js:28 shortfuts: SyntaxError: Unexpected end of JSON input
logError @ commonUtility.js:28
xhr.onreadystatechange @ script.js:215
XMLHttpRequest.send (async)
getFutbinData @ script.js:220
(anonymous) @ script.js:78
safeCallbackApply @ VM316 extensions::uncaught_exception_handler:27
handleResponse @ VM317 extensions::sendRequest:67
commonUtility.js:28 shortfuts: Unable to get Futbin data.

**Comment by martellaj** [comment]
Darn. The request didn't have any security issues when using local code. Rules must be different when using the extension from the store. Thanks for reporting - I'll take a look ASAP.

On mobile, so please excuse any errors or brevity.
________________________________

**Comment by martellaj** [comment]
Fixed! Thanks!
