### ISSUE TITLE
Add a "store all items" shortcut

### ISSUE THREAD

**Issue by martellaj** [martellaj/shortfuts#5]
Requested by /u/TOTYgavin.

**Comment by SubNoizey** [comment]
+1

**Comment by martellaj** [comment]
Erg, unable to get a click on "Store all items". I was able to simulate it, but it just takes longer than clicking, so it doesn't fit. Closing for now. Might revisit ability in the future, but I can't get a click on those damn buttons.

**Comment by martellaj** [comment]
@SubNoizey Added in 3.2.0!
