### ISSUE TITLE
Search Button

### ISSUE THREAD

**Issue by nokai** [martellaj/shortfuts#53]
Why do not you recognize the tap of the search button?

`function clickSearchButton () {
    // throw 'This shortfut is in development.';
commonUtility.log (`Attempting to press Search button ...`);
     try {
         const searchButton = document.getElementsByClassName ('btn btn-raised call-to-action') [0];
         _tapElement (searchButton);
     } catch (error) {
         commonUtility.logError (error);
         throw 'Unable to click "Search" button.';
     }
}`

**Comment by martellaj** [comment]
Because it doesn't work. I've been unable to fake clicks on buttons in the central part of the page. Feel free to take a crack at it though!

On mobile, so please excuse any errors or brevity.
________________________________

**Comment by nokai** [comment]
The extension is fine, but to improve you have to snipe the cards.

I'll try to make it work.

Thanks for your work

**Comment by martellaj** [comment]
Why did you close? No luck?

**Comment by nokai** [comment]
Exactly. If I get it to work, I'll write it here. a greeting
