### ISSUE TITLE
Allow users to map custom key bindings

### ISSUE THREAD

**Issue by martellaj** [martellaj/shortfuts#6]
- Include link to where user can change assigned hotkeys in popup

**Comment by soikmd2** [comment]
@martellaj have you abbandoned this great extension?

**Comment by martellaj** [comment]
@soikmd2 It's not abandoned... chugging along just fine with about 400 users a day. I don't play FUT anymore and haven't received any donations, so no more work is going into it.

**Comment by martellaj** [comment]
@soikmd2 After checking user data last night, I'm actually planning to revamp this for FIFA 19 (maybe earlier), and this will be included. Stay tuned!

**Comment by soikmd2** [comment]
wow! glad to hear that @martellaj!!

**Comment by martellaj** [comment]
Done in v3.
