### ISSUE TITLE
Add shortcut for pagination

### ISSUE THREAD

**Issue by soikmd2** [martellaj/shortfuts#72]
Hey Joe @martellaj !

Consider to add new shortcuts to paginate Next and Previous pages.

You as nobody else know that sometimes we can't stand using mouse and just want to hang on keyboard so...

Would be great if you binded left and right arrows to navigate on Market Search results, Club, SBC Club/Concept search results, compared cards, well.. all pages that we can get several items displayed with pagination.

Arrows or Num_pad arrows (4 and 6)

;)

**Comment by martellaj** [comment]
Thanks for the suggestion, @soikmd2. Sounds like a good candidate for a new shortcut to me, so I'll investigate. Also feel free to take a crack at it (just let me know if you're working on it please).
