### ISSUE TITLE
Hi... Great Work

### ISSUE THREAD

**Issue by nokai** [martellaj/shortfuts#76]
Very good work...

How do you do the extensions now? They used to be javascript. Now I do not see the js files.

**Comment by martellaj** [comment]
Please refer to the _src_ folder. Back in the spring (March or April?), I converted the project to TypeScript.

**Comment by nokai** [comment]
And how can the extension be exported to Chrome?
I'm trying to drag the folder but it gives me an error.

**Comment by martellaj** [comment]
This is just the source code. You can install via the [Chrome Web Store](https://chrome.google.com/webstore/detail/shortfuts/ohflhgdonldacinnfhddlgcnppekidje).
