### ISSUE TITLE
Transfer search DK Keyboard

### ISSUE THREAD

**Issue by Andersdyr** [martellaj/shortfuts#79]
Hi,

the Search with = doesn't seems to work on Danish keyboard, as i have to press "Shift + 0", to get the "="

Maybe it will be better with the enter button? :) 

![image](https://user-images.githubusercontent.com/43519436/45929655-19285880-bf55-11e8-8a7b-6935946fcd7b.png)

**Comment by martellaj** [comment]
I'm closing this issue because there's already a solution here - using the configurable shortcuts. I'm not interested in improving the legacy hotkeys too much... they were meant to be replaced anyway.
